### ISSUE TITLE
Naming Discussion:  OptimTraj, or something better?

### ISSUE THREAD

**Issue by MatthewPeterKelly** [MatthewPeterKelly/OptimTraj#13]
It seems that the name TrajOpt is already taken by a [software package](http://rll.berkeley.edu/trajopt/ijrr/) from Pieter Abeel's group at Berkeley. 

This library should be renamed. So far the best that I've come up with is OptimTraj, but I'm open to suggestions.

**Comment by delyle** [comment]
I have a few ideas (from most to least preferred). Don't know if any of these are taken: 

* OTSo - Optimal Trajectory Software (also the name of a [mythical bear](https://en.wikipedia.org/wiki/Otso])

* OpTool - Optimization Toolbox

* MaTrOS - Matlab Trajectory Optimization Software (pronounced "Mattress")

**Comment by MatthewPeterKelly** [comment]
Hi Delyle,

Thanks for the input!  I actually updated the name two days ago from TrajOpt to OptimTraj, and forgot to close out this thread. 

That being said, I really appreciate the feedback, and I do like your first suggestion: OTSo. I'll leave the thread open for a bit, to see if anyone else wants to weigh in. There are two other software programs called OTSo that I could find, but neither are related to trajectory optimization.

Matt
