### ISSUE TITLE
Why does OptimTraj print out the following message, even for the demo examples?

### ISSUE THREAD

**Issue by stumarcus576** [MatthewPeterKelly/OptimTraj#15]
When I run OptimTraj, it prints out the message below. Perhaps OptimTraj could be modified to prevent this message from being printed.

Your initial point x0 is not between bounds lb and ub; FMINCON
shifted x0 to strictly satisfy the bounds.

**Comment by stumarcus576** [comment]
When I run OptimTraj, it prints out the message below. Perhaps OptimTraj could be modified to prevent this message from being printed.

Your initial point x0 is not between bounds lb and ub; FMINCON
shifted x0 to strictly satisfy the bounds.

**Comment by MatthewPeterKelly** [comment]
FMINCON prints out that warning whenever the initial guess is "sitting" on a constraint. For example, consider a variable "x", with the following constraints: x <= 0, x >=0, and the initial guess is x=0. It might be possible to kill this with some clever preprocessing, but I never got around to it.
