### ISSUE TITLE
Vectorized Gradients for OptimTraj Example Problems

### ISSUE THREAD

**Issue by stumarcus576** [MatthewPeterKelly/OptimTraj#26]
Which symbolic solver was used to generate the gradients for the OptimTraj example problems? Does that symbolic solver directly generate vectorized gradients, because it looks like the analytic gradients implemented in the OptimTraj examples have all been vectorized.

**Comment by MatthewPeterKelly** [comment]
* All of my symbolics for OptimTraj are done using the Matlab Symbolic Toolbox. It is actually pretty powerful, if you learn a few non-obvious commands. I have published the source code to derive every automatically generated function in OptimTraj. They are all scripts that follow the naming pattern: "Derive_*.m".

* All of my gradients are vectorized. This required a big effort on my part when writing the code, as the Matlab Symbolic Toolbox does not support this feature well. This follows through in both the user-defined code (Demos) and in the source code (eg. hermiteSimpson.m).
