### ISSUE TITLE
How to cite OptimTraj?

### ISSUE THREAD

**Issue by stumarcus576** [MatthewPeterKelly/OptimTraj#28]
Is there a recommended way to cite OptimTraj in academic research? A BibTeX entry would be especially useful.

**Comment by MatthewPeterKelly** [comment]
I wrote a tutorial paper about trajectory optimization, which includes this software. The paper should be published in the next few months. Once it is, I will direct people to cite that paper for this software.

In the mean time, it is probably best to cite the [user's guide](https://github.com/MatthewPeterKelly/OptimTraj/blob/master/docs/UsersGuide/OptimTraj_UsersGuide.pdf):

OptimTraj User's Guide, Version 1.5
Matthew P. Kelly
May 27, 2016
https://github.com/MatthewPeterKelly/OptimTraj

**Comment by MatthewPeterKelly** [comment]
Sure -- done!
