### ISSUE TITLE
long run time

### ISSUE THREAD

**Issue by aknikzad94** [MatthewPeterKelly/OptimTraj#30]
Hi,
I'm solving a optimal control problem with your great solver,
but some times it took so so long time to show the results, I attached a sample picture,
Is there any trick like changing the stopping criteria to resolve this problem?
![capture123](https://user-images.githubusercontent.com/30901480/29173396-659524a4-7df8-11e7-9610-6a0bf4507acd.PNG)

**Comment by MatthewPeterKelly** [comment]
Hi aknikzad94,

I would need more details to make any real diagnosis of the issue. That being said, my guess is that there is an issue with your problem statement: the solution is either non-unique, or the gradients of your objective and constraint functions are not smooth. These can both be studied by careful tests on your problem statement, and are discussed in some detail in my tutorial paper on the topic:
[tutorial paper](http://www.matthewpeterkelly.com/research/MatthewKelly_IntroTrajectoryOptimization_SIAM_Review_2017.pdf)
More resources here:
[tutorial website](http://www.matthewpeterkelly.com/tutorials/trajectoryOptimization/)

If you problem statement is fully debugged, then you can adjust both the optimality and feasibility tolerances in OptimTraj. If can be done by setting the
`problem.options.nlpOpt` struct, as described in the
[user's guide](https://github.com/MatthewPeterKelly/OptimTraj/blob/master/docs/UsersGuide/OptimTraj_UsersGuide.pdf)
You can get an example of the default value of this struct by typing at the Matlab command prompt:
`default_nlpOpt = optimset('fmincon')`

Best of luck,

Matt
