### ISSUE TITLE
OptimTraj User Documentation error: Path and Boundary Constraints

### ISSUE THREAD

**Issue by KosteonLink** [MatthewPeterKelly/OptimTraj#34]
The documentation PDF states (page 3, section 2.2) that for the path and boundary constraint functions, the first output should be the equality constraint and the second output should be the inequality constraint.

However, the comments in the OptimTraj function itself (optimTraj.m) state that the first output is the _in_equality constraint and the second is the equality constraint. My experimentation with the function has revealed that this is correct and that the documentation is mistaken.

**Comment by MatthewPeterKelly** [comment]
@KosteonLink - thanks for letting me know about the mistake in the documentation! 

Let me know if you find any other errors, or if you have other suggestions for the software. My plan is to make some improvements to OptimTraj this summer.
