### ISSUE TITLE
How to add time-varying control bounds

### ISSUE THREAD

**Issue by Enigma000** [MatthewPeterKelly/OptimTraj#37]
How can I add a time-varying control bounds to my problem?
Such as the control bounds varies with the state of the system.

**Comment by MatthewPeterKelly** [comment]
You can add a time-varying control bound to your problem by defining a path constraint function. In the help / documentation it shows up as:

```matlab
% INPUT: "problem" -- struct with fields:
%
%   func -- struct for user-defined functions, passed as function handles
%
% ...
%       [c, ceq] = pathCst(t,x,u)
%               c = column vector of inequality constraints  ( c <= 0 )
%               ceq = column vector of equality constraints ( c == 0 )
```

For a bound, you probably want to specify an inequality constraint (`c`) rather than an equality constraint (`ceq`).
