### ISSUE TITLE
Error using trapezoid/rungeKutta methods but none with chebyshev

### ISSUE THREAD

**Issue by niksknocksu** [MatthewPeterKelly/OptimTraj#49]
I get the following error while using trapezoid/rungeKutta methods only. My problem is of a reentry vehicle optimization with 8 states, 2 controls, and an objective to minimize time. I can use the Chebyshev method though it never converges.

![image](https://user-images.githubusercontent.com/41114459/142960846-98ed12e8-cf7e-4100-b8d0-f78c4c913c12.png)

**Comment by MatthewPeterKelly** [comment]
Hmmm... This looks like a problem in the user-supplied dynamics function. Is it properly vectorized? It should return an array with size of '[nState, nTime]' when passed the state and time at every collocation point.

The 'Chebyshev' method is somewhat less rigorously tested than other methods. I suggest avoiding it and using either the trapezoid or Hermite--Simpson methods instead.

**Comment by niksknocksu** [comment]
That was indeed the problem.  I didn't realize that the function had to be vectorized.

Thank you very much!
