### ISSUE TITLE
Handle multi-phase problems

### ISSUE THREAD

**Issue by AlessandroZavoli** [MatthewPeterKelly/OptimTraj#53]
Many optimal control problems can be more easily solved by splitting the trajectory into multiple phases, joint by some interface (e.g., continuity/discontinuity) conditions.

Would it be possible to add this feature?

**Comment by MatthewPeterKelly** [comment]
Yeah: support for multi-phase optimization would be great. I've already got an issue open for this (https://github.com/MatthewPeterKelly/OptimTraj/issues/9), so I'm going to close this one as a duplicate.

I'm no longer actively working on OptimTraj, so it is unlikely that this feature will be added as of now. In principle it wouldn't be too hard. The main challenge would be extending the API in a way that kept the core solver easy to use.
