### ISSUE TITLE
Constraints on the Control Inputs

### ISSUE THREAD

**Issue by AhmedMAtallah** [MatthewPeterKelly/OptimTraj#54]
Can I have a constraint on the control input such that '||\mathbf{u}||<=u_{max}'?

**Comment by MatthewPeterKelly** [comment]
I think so!  You would use the path constraint:
https://github.com/MatthewPeterKelly/OptimTraj/blob/27bcf50697a0a8ec95fbe729b418d0fd72b66f3b/optimTraj.m#L28-L30

It will probably behave better if you square both sides, so that you don't end up with a square root in your constraint.
